author: Christopher Bacon
theme: jekyll-theme-hacker
title: The Abominable Land of Pure Code
description: A rum soaked paradise

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

sass:
  style: :compressed
