author: Christopher Bacon
theme: jekyll-theme-hacker
title: The Abominable Land of Pure Code
description: A rum soaked paradise

sass:
  style: :compressed

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

talks:
  - location: Manchester Lambda Lounge
    name: "Haskell at Tracsis: Some lessons"
    url: https://docs.google.com/presentation/d/1IG-LyNSYFBU9bSRzabWlhHHRsM-7961suQqv-tcngpA/edit?usp=sharing
  - location: Tracsis
    name: Pair Programming
    url: https://docs.google.com/presentation/d/1smd0OJ6coV8jYMA0tJx897ut-hSQs0_BQkRm-55Oer4/edit?usp=sharing
  - location: Manchester Lambda Lounge
    name: Using Monoids to Build UI
    url: https://docs.google.com/presentation/d/1y6y9VqRxBNUngF9t4qi_9n7cRA8m5eL5R0X8TG3DWBY/edit?usp=sharing
  - location: BBC
    name: "Haskell: Programming Purity"
    url: https://docs.google.com/presentation/d/1Al3J9S6MlOy_1X9wfaTqpxofZ6NGjDgZwmzjHYLuA9s/edit?usp=sharing

technologies:
  - Haskell
  - JS (React/Node)
  - TypeScript
  - Elm
  - Python
  - Bash
  - Unix
  - Git
  - Ansible
  - AWS
  - LaTeX

oss_projects:
  - name: Exosphere
    url: https://github.com/exosphere-lang/compiler
    description: A high level AWS CloudFormation language and compiler
  - name: Haskell Refactor
    url: https://github.com/chris-bacon/haskell-refactor
    description: A lightweight vim plugin that helps you refactor Haskell code

oss_patches: 
  - name: GHC
    url: https://github.com/ghc/ghc/commit/36c1431d9d2d06049190cc0888dbfaee8e2179d6
    commitRef: 36c1431d9d2d06049190cc0888dbfaee8e2179d6
  - name: "Vim-one: colorschemes for Vim"
    url: https://github.com/rakr/vim-one/commit/8e1118ecec916e1334694a44ef29db70fb679682>
    commitRef: 8e1118ecec916e1334694a44ef29db70fb679682
  - name: "Intero-neovim: an intero plugin for neovim"
    url: https://github.com/parsonsmatt/intero-neovim/commit/26d340ab0d6e8d40cbafaf72dac0588ae901c117
    commitRef: 26d340ab0d6e8d40cbafaf72dac0588ae901c117

cards:
  - title: Tracsis
    thumbnail: https://kandl-genres.files.bbci.co.uk/kandl-genres/1233-1/images/meta-images/bbc_blocks.png 
    summary: test test test

  - title: BBC
    thumbnail: https://kandl-genres.files.bbci.co.uk/kandl-genres/1233-1/images/meta-images/bbc_blocks.png
    summary: test test test
