author: Christopher Bacon
theme: jekyll-theme-hacker
title: The Abominable Land of Pure Code
description: A rum soaked paradise

sass:
  style: :compressed

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"


talks:
  - 
    - location: Manchester Lambda Lounge:
    - name: Haskell at Tracsis (Some lessons)
    - url: https://docs.google.com/presentation/d/1IG-LyNSYFBU9bSRzabWlhHHRsM-7961suQqv-tcngpA/edit?usp=sharing
